### ISSUE TITLE
メソッド名とプロパティをcamelCaseに統一する

### ISSUE THREAD

**Issue by Yosuke-Aramaki** [Yosuke-Aramaki/leo#21]
メソッド名とプロパティにcamelCaseとsnake_caseが混ざっています。camelCaseに統一したいです。

_Originally posted by @ichigotake in https://github.com/Yosuke-Aramaki/gx_app_3/pull/1#discussion_r473687362_

**Comment by Yosuke-Aramaki** [comment]
関数名とNuxtで完結するプロパティーに関してはcamelCaseに統一いたしました。

Rails APIのプロパティーをsnake_caseで書いてるため、Nuxtのフォームで渡す変数はsnake_caseで書いているのですが、Railsのパラメーターも含めてcamelCaseに変更した方が良いでしょうか?

**Comment by ichigotake** [comment]
APIのフィールド名は好みの問題かなと思ってます。
snake_caseの公開APIは多いですしね。

>関数名とNuxtで完結するプロパティーに関しては

この意識が重要で、一般論としては「外部（APIやSDK等）の仕様はクライアントの手が及ばない範囲だから仕方ない」という判断になると思います。

**Comment by Yosuke-Aramaki** [comment]
コメントありがとうございます！
承知しました、APIの方はsnake_caseのままで開発を続けます、ありがとうございます
